### ISSUE TITLE
Add number of source code lines to node

### ISSUE THREAD

**Issue by UncleGene** [seattlerb/sexp_processor#14]
As per https://github.com/seattlerb/flay/issues/30

External tools using flog/flay would benefit a lot from knowing number of source code lines corresponding to each node. At this moment all tools have to speculate about number of lines (by checking start line in nested nodes), that results in being off, usually by number of block closing lines (-1)

**Comment by zenspider** [comment]
I've added `Sexp.line_max` which effectively closes this out. Finally.
