### ISSUE TITLE
The method #s brings trouble

### ISSUE THREAD

**Issue by 5minpause** [seattlerb/sexp_processor#16]
Hi there.

I just wanted to note, that the definition of #s in `lib/sexp.rb` brings trouble for other gems where a #s method is defined.

I noticed it for our CMS gem Goldencobra. We have a class `Goldencobra::Setting` where we save application wide settings. There exists a helper method for accessing settings in views (conveniently named `s`) that doesn't work anymore after adding pronto-flay (and sexp_processing) to the project.

Here's your definition.
``` ruby
##
# This is a very important shortcut to make using Sexps much more awesome.

def s(*args)
  Sexp.new(*args)
end
```

I am no Ruby expert that's why I am asking: What could be done to prevent this from happening?

Best regards,
Holger

**Comment by presidentbeef** [comment]
Do you have a line like this in your Gemfile?

```
gem "pronto-flay"
```

If so, change it to

```
gem "pronto-flay", :require => false
```

and don't use `rake` to run Pronto.

Basically, you don't want to actually load Pronto or any static analysis tools into your application, and Bundler will just load up everything unless you tell it not to.

**Comment by zenspider** [comment]
Closing.
