### ISSUE TITLE
Deep_clone method name conflict

### ISSUE THREAD

**Issue by moiristo** [seattlerb/sexp_processor#19]
Hi there,

A user of my gem 'deep_cloneable' brought up that we have a name conflict, as my gem introduces deep_clone and yours does as well (https://github.com/seattlerb/sexp_processor/blob/master/lib/sexp_processor.rb#L657). See moiristo/deep_cloneable#24.

I'm not sure yet what the best solution is for this problem, but I thought it would be good to at least notify you of this issue.

**Comment by zenspider** [comment]
Argh. Sorry. How do you want to go about this? I'd rather not declare a dependency on your code as the scope is too big. Are we functionally compatible? If so, is there a guard we can both use?

**Comment by zenspider** [comment]
Anything?

**Comment by zenspider** [comment]
You've done a release in the last 10 days... so... you're active on that project. No feedback?

**Comment by moiristo** [comment]
Ah, sorry, forgot about this one; I took some time off ;) My gem is used for duping ActiveRecord objects including associations (shallow), so we're definitely not compatible. Do you really need this method on Object? My method definition only applies to ActiveRecord::Base objects.

**Comment by zenspider** [comment]
What's the actual conflict? I don't see the error as it pertains to `deep_clone`, just `dup`.

**Comment by moiristo** [comment]
It's not really about the issue report itself, I was talking about this comment, which explains the conflict in detail: https://github.com/moiristo/deep_cloneable/issues/24#issuecomment-146380132.

**Comment by zenspider** [comment]
> On Jan 21, 2016, at 16:31, Reinier de Lange <notifications@github.com> wrote:
> 
> It's not really about the issue report itself, I was talking about this comment, which explains the conflict in detail: moiristo/deep_cloneable#24 (comment). 
> 
> 

Except that it doesn't... the error is what is missing. As is a repro.

**Comment by moiristo** [comment]
True. I know that it is about the wrong number of arguments error (1 for 0) though.. It's fine with me to leave things as they are right now until we can reproduce the error or receive more bug reports. It doesn't seem like my gem and yours are often being used in the same application anyway.

**Comment by zenspider** [comment]
Agreed. Closing until we need this.
