### ISSUE TITLE
ArgumentError: setting line with non-integer

### ISSUE THREAD

**Issue by nhoffmann** [seattlerb/sexp_processor#28]
I am trying to understand a bug in our codebase that surfaced since ce284487f057203360c41b14d2b25f8c5453fbb9 got introduced. We are using brakeman which depends on `sexp_processor` and after a change, a very unrelated piece of code raises the `ArgumentError` introduced by this commit. Unfortunately I am having a hard time understanding what is going on. Can somebody shed some light on why this change is necessary and what causes the line to be set with a non-integer in the first place? Thank you very much!

**Comment by morozRed** [comment]
Hey @nhoffmann, got stuck with the same error today.
In my case it looks like breakman or pronto-breakman is passing a nil to this function so it raises. Fixed it by using previous version: `gem 'sexp_processor', '4.12.0'`.

**Comment by presidentbeef** [comment]
If the issue is with Brakeman, then see https://github.com/presidentbeef/brakeman/issues/1362

You can pin `sexp_processor` to an older version, use the unreleased version of Brakeman, or just ensure Brakeman is loaded before whatever is loading `sexp_processor`.

**Comment by nhoffmann** [comment]
Thank you very much for the replies. We are experiencing what @morozRed descibes and yes, we pinned `sexp_processor` to version `4.12.0` to fix the problem temporarily.
I was just wondering where the error came from, if it is from our codebase, a bug in brakeman or sexp_processor. What got me confused was, that the error occurred after a change in a very unrelated piece of code 😄 

Glad to hear that the next version of brakeman will contain a fix. Thank you so much for your work @presidentbeef!
